### PR TITLE
terminal: Properly set raw terminal only when needed

### LINKED ISSUE #22: terminal: Fix setup of raw terminal
We should be able to prevent the import of `github.com/moby/moby/pkg/term` package since we can program the raw terminal with some simple functions coming from the more generic package `golang.org/x/sys/unix`.
Also, we need to ensure we are setting the raw terminal only if STDIN is a terminal, otherwise the function call will fail.

### PR DESCRIPTION
**Pull request by sboeuf**
This commit relies on unix package from golang instead of moby/moby
to get the terminal setup in raw mode.
Also, it fixes an issue about the terminal being set in raw mode
every time, even when STDIN was not a terminal.

Fixes #22

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

File: terminal.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+//
+// SPDX-License-Identifier: Apache-2.0
+//
+
+package main
+
+import (
+	"os"
+
+	"golang.org/x/sys/unix"
```
Comment (bergwolf) [inline terminal.go]: One benefit of importing "github.com/moby/moby/pkg/term" is that we do not have OS specific code.

Comment (WeiZhang555) [reply terminal.go]: Good point. 

If this is unix specific, we should add build tag 
```
// +build linux
```

or rename this file to `terminal_linux.go`

Comment (sboeuf) [reply terminal.go]: @bergwolf @WeiZhang555 I get the point, but do we care about this code being portable to something else than Linux ?

Comment (sboeuf) [reply terminal.go]: @WeiZhang555 I have renamed the file to `terminal_linux.go`.
@bergwolf I didn't like that we were relying on a docker package for that. Also, this commit actually solves a real issue because we were not checking if STDIN was a terminal, meaning we were failing when trying to set the terminal as RAW in case it was not a terminal.

Comment (bergwolf) [reply terminal.go]: fair enough. Let's take this for now and add other OS support when necessary.

**Comment by bergwolf** [comment]
LGTM

**Comment by laijs** [comment]
for checking "if needed", I prefer to add an argument as #12

**Comment by sboeuf** [comment]
@laijs sorry I don't understand what you expect me to do here.

**Comment by sboeuf** [comment]
@sameo PTAL

**Comment by bergwolf** [comment]
@sboeuf I think @laijs wanted to add an shim command line argument to let shim know that STDIN is a terminal or not, like @teawater did in #12. @laijs please correct me I misunderstood.

**Comment by laijs** [comment]
Whether the process's stdio is a terminal or not is one of the configurations which should be passed via canonical way which is the command line argument for shim.

Sure, we can detect the configuration from the shim's stdio via ioctl, but we should use ioctl to detect whether it is a terminal or not at first. 'err != nil' is not reliable, there might be of other kinds of error. Even though I insist on the canonical way. The shim only does the things when requested. It doesn't need to be so smart and so automatic.

**Comment by sboeuf** [comment]
@laijs ok fair enough, I'll do this check from the runtime in order to provide a parameter to the shim.

**Comment by sameo** [comment]
@laijs 
> 'err != nil' is not reliable, there might be of other kinds of error.

It actually is. golang's ioctl is a syscall wrapper, and there are not many ways this particulat syscall can fail (probably the only failures are about the fd not being valid or the kernel->userspace copy failing, in both cases, we should not consider the fd as a terminal). As a matter of fact, golang's ssh/terminal package just use this exact code.

Assuming the ioctl check is reliable, I don't think there's any reason for keeping the shim dumb when there are reliable ways to make it robust.

**Comment by sboeuf** [comment]
@laijs have you any comment about what @sameo said ?
I'd like we all agree on something pretty quickly here so that we can move forward and so that we get something functional asap.

**Comment by sboeuf** [comment]
@laijs @sameo nevermind, I have made the change to this PR so that we provide a `terminal` flag in order to specify a terminal has been setup.

**Comment by laijs** [comment]
LGTM
but the codecov/project complains.
Cloud you add some test for the newly added function?

**Comment by sboeuf** [comment]
Yes sure I can do that.

**Comment by sameo** [comment]
LGTM

**Comment by sboeuf** [comment]
@laijs PR updated adding some unit tests.

**Comment by sameo** [comment]
@laijs Please merge it if it's fine with you. It is ok for me.

**Comment by bergwolf** [comment]
lgtm

**Comment by laijs** [comment]
LGTM
